Play 1.2.1

diff --git a/install_play b/install_play
--- a/install_play
+++ b/install_play
@@ -1,22 +1,29 @@
 #!/bin/sh
 
-VERSION=1.1
+if [ ! $1 ]
+then
+    echo 'Missing the first argument - version number for Play to install.'
+    exit 1
+fi
+
+VERSION=$1
 MODULE_NAME=play-${VERSION}
 WORK_DIR=${MODULE_NAME}
 ZIP_FILE_NAME=${MODULE_NAME}.zip
-TARGET_DIR=~/app
+TARGET_DIR=~/Library/Play
 
 mkdir ${WORK_DIR}
 cd ${WORK_DIR}
 wget http://download.playframework.org/releases/${ZIP_FILE_NAME}
 unzip ${ZIP_FILE_NAME}
+rm $ZIP_FILE_NAME
 
 mkdir -p ${TARGET_DIR}
 mv ${MODULE_NAME} ${TARGET_DIR}
 
 # install my favorite play plugins
 
-PLUGINS='gae siena scala maven'
+PLUGINS='scala'
 
 cd ${TARGET_DIR}/${MODULE_NAME}
 
